<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class CreateSubjectsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('subjects', function (Blueprint $table) {
            $table->id();
            $table->string('name');
        });

        $subject_list = [
            "Agrimensura",
            "Agroecologia",
            "Agroindústria",
            "Agronomia",
            "Análise e Desenvolvimento de Sistemas",
            "Aquacultura",
            "Administração",
            "Arqueologia",
            "Arquitetura",
            "Arquitetura e Urbanismo",
            "Arquivística",
            "Artes Cênicas",
            "Artes Visuais",
            "Astronomia",
            "Automação Industrial",
            "Biblioteconomia",
            "Biocombustíveis",
            "Bioengenharia",
            "Biofísica",
            "Biologia ",
            "Biomedicina",
            "Biotecnologia",
            "Botânica",
            "Cafeicultura",
            "Ciências Aeronáuticas",
            "Ciências Atuariais",
            "Ciências Biomoleculares",
            "Ciências Humanas",
            "Ciências Matemáticas da Terra",
            "Ciências Naturais",
            "Ciências Sociais",
            "Cinema",
            "Comércio Exterior",
            "Construção de Edifícios",
            "Construção de Estradas",
            "Construção Naval",
            "Contabilidade",
            "Cooperativismo",
            "Cosmetologia",
            "Dança",
            "Defesa e Gestão Estratégica Internacional",
            "Desenho Industrial",
            "Design de Interiores",
            "Design de Moda",
            "Direito",
            "Drenagem",
            "Ecologia",
            "Economia  ",
            "Economia Doméstica",
            "Editoração",
            "Educação Artística",
            "Energias Renováveis",
            "Enfermagem",
            "Engenharia Aeroespacial",
            "Engenharia Agrícola",
            "Engenharia Ambiental",
            "Engenharia Cartográfica",
            "Engenharia Civil",
            "Engenharia da Computação",
            "Engenharia de Alimentos",
            "Engenharia de Materiais",
            "Engenharia de Minas",
            "Engenharia de Pesca",
            "Engenharia de Petróleo",
            "Engenharia de Produção",
            "Engenharia de Sistemas Eletrônicos",
            "Engenharia de Softwares",
            "Engenharia de Telecomunicações",
            "Engenharia Elétrica",
            "Engenharia Física",
            "Engenharia Florestal",
            "Engenharia Industrial Madeireira",
            "Engenharia Mecânica",
            "Engenharia Mecatrônica",
            "Engenharia Metalúrgica",
            "Engenharia Militar",
            "Engenharia Naval e Oceânica",
            "Engenharia Nuclear",
            "Engenharia Química",
            "Engenharia Sanitária",
            "Engenharia Têxtil",
            "Enologia",
            "Escultura",
            "Esporte e Lazer",
            "Estatística",
            "Eventos",
            "Farmácia",
            "Filosofia",
            "Física",
            "Física Computacional",
            "Fisioterapia",
            "Fonoaudiologia",
            "Fotografia",
            "Gastronomia",
            "Geofísica",
            "Geografia",
            "Geologia",
            "Geoprocessamento e Sensoriamento Remoto",
            "Gerontologia",
            "Gestão Ambiental",
            "Gestão Comercial",
            "Gestão de Petróleo e Gás",
            "Gestão de Segurança Privada",
            "Gestão do Agronegócio",
            "Gestão Financeira",
            "Gestão Hospitalar",
            "Gestão Pública",
            "Gravurismo",
            "História",
            "História da Arte",
            "Hotelaria",
            "Indústria da música",
            "Informática  ",
            "Jornalismo",
            "Letras - Português",
            "Letras - Inglês",
            "Letras - Espanhol",
            "Letras - Francês",
            "Letras - Italiano",
            "Letras - Alemão",
            "Letras - Outras línguas",
            "Linguística",
            "Logística",
            "Manutenção Industrial",
            "Marketing",
            "Matemática  ",
            "Matemática Aplicada",
            "Mecatrônica e Mecânica de Precisão",
            "Medicina  ",
            "Medicina Veterinária",
            "Meliponicultura",
            "Mercado Imobiliário",
            "Mercadologia",
            "Meteorologia",
            "Microbiologia e Imunologia",
            "Mineração",
            "Museologia",
            "Música",
            "Nanotecnologia",
            "Naturologia",
            "Neurociência",
            "Nutrição",
            "Oceanografia",
            "Odontologia",
            "Paisagismo",
            "Pedagogia",
            "Pintura",
            "Processamento de Dados",
            "Processos Metalúrgicos",
            "Produção Audiovisual",
            "Produção Cultural",
            "Produção Têxtil",
            "Psicologia",
            "Química",
            "Quiropraxia",
            "Radiologia",
            "Recursos Humanos",
            "Redes de Computadores",
            "Redes de Telecomunicações",
            "Relações Internacionais",
            "Relações Públicas",
            "Saneamento Ambiental",
            "Secretariado",
            "Segurança no Trabalho",
            "Segurança Pública",
            "Serviço Social",
            "Sistemas Biomédicos",
            "Sistemas de Informação",
            "Sistemas Elétricos",
            "Sistemas para Internet",
            "Sociologia",
            "Teatro",
            "Teologia",
            "Transporte Terrestre",
            "Turismologia",
            "Urbanismo",
            "Zootecnia",
            "Ciências Contábeis",
            "Gestão de Dados",
            "Processos Gerenciais",
            "Banco de Dados",
            "Computação em Nuvem",
            "Jogos Digitais",
            "Engenharia de Computação",
            "Sistema de Informação",
            "Administração escolar",
            "Biologia marinha",
            "Ciência da computação",
            "Ciência dos alimentos",
            "Ciência dos materiais",
            "Ciência Política",
            "Ciências agrárias",
            "Ciências biológicas",
            "Ciências da saúde",
            "Ciências do meio aquático",
            "Comunicação social",
            "Design de Jogos Digitais",
            "Design de produto",
            "Design gráfico",
            "Educação física",
            "Engenharia aeronáutica",
            "Engenharia biomédica",
            "Engenharia de controle e automação",
            "Engenharia geológica",
            "Física médica",
            "Gestão da Qualidade",
            "Gestão da Tecnologia da Informação",
            "Informática biomédica",
            "Matemática computacional",
            "Publicidade e Propaganda",
            "Química ambiental",
            "Química industrial",
            "Saúde pública",
            "Tecnologia em oftálmica",
            "Tecnólogo em logística",
            "Terapia ocupacional",
            "Transporte aéreo",
            "Engenharia de manufatura",
            "Engenharia de Tecidos",
            "Estética",
            "Fruticultura",
            "Gestão Portuária",
            "Horticultura",
            "Obstetrícia",
            "Ordenamento do Território",
            "Produção de Aguardente",
            "Produção de Laticínios",
            "Produção de Materiais Plásticos",
            "Produção Sucroalcooeira",
            "Recursos hídricos",
            "Segurança da Informação",
            "Silvicultura",
            "Sistemas de Navegação Fluvial",
            "Sistemas Embarcados",
            "Telemática",
        ];

        sort($subject_list);

        foreach($subject_list as $index) {
            DB::table('subjects')->insert(['name' => $index]);
        }

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('subjects');
    }
}
